// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PR.Persistence.EntityFrameworkCore.Sqlite;

#nullable disable

namespace PR.Persistence.EntityFrameworkCore.Sqlite.Migrations
{
    [DbContext(typeof(PRDbContext))]
    partial class PRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("PR.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Dead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Superseded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PR.Domain.Entities.PersonAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjectPersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjectPersonObjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectPersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectPersonObjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Superseded")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjectPersonId");

                    b.HasIndex("SubjectPersonId");

                    b.ToTable("PersonAssociations");
                });

            modelBuilder.Entity("PR.Domain.Entities.PersonAssociation", b =>
                {
                    b.HasOne("PR.Domain.Entities.Person", "ObjectPerson")
                        .WithMany("SubjectPeople")
                        .HasForeignKey("ObjectPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.Person", "SubjectPerson")
                        .WithMany("ObjectPeople")
                        .HasForeignKey("SubjectPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectPerson");

                    b.Navigation("SubjectPerson");
                });

            modelBuilder.Entity("PR.Domain.Entities.Person", b =>
                {
                    b.Navigation("ObjectPeople");

                    b.Navigation("SubjectPeople");
                });
#pragma warning restore 612, 618
        }
    }
}
