// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PR.Web.Persistence;

#nullable disable

namespace PR.Web.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250614111244_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.CoordinateSystem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CoordinateSystem");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.LinePoint", b =>
                {
                    b.Property<Guid>("LineID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PointId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("LineID", "Index");

                    b.HasIndex("PointId");

                    b.ToTable("LinePoint");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.VerticalDistance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Dimension")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("VerticalDistance");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.ObjectItems.ObjectItem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativeIdentificationText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ObjectItems");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PR.Domain.Entities.PR.Person", b =>
                {
                    b.Property<Guid>("ArchiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Dead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ID")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Superseded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("ArchiveID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PR.Domain.Entities.PR.PersonAssociation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArchiveID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjectPersonArchiveID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjectPersonID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectPersonArchiveID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectPersonID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Superseded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ObjectPersonArchiveID");

                    b.HasIndex("SubjectPersonArchiveID");

                    b.ToTable("PersonAssociation");
                });

            modelBuilder.Entity("PR.Domain.Entities.PR.PersonComment", b =>
                {
                    b.Property<Guid>("ArchiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonArchiveID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Superseded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ArchiveID");

                    b.HasIndex("PersonArchiveID");

                    b.ToTable("PersonComments");
                });

            modelBuilder.Entity("PR.Domain.Entities.Smurfs.Smurf", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Smurfs");
                });

            modelBuilder.Entity("PR.Web.Persistence.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.PointReference", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.CoordinateSystem");

                    b.Property<Guid>("OriginPointID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("XVectorPointID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("YVectorPointID")
                        .HasColumnType("TEXT");

                    b.HasIndex("OriginPointID");

                    b.HasIndex("XVectorPointID");

                    b.HasIndex("YVectorPointID");

                    b.ToTable("PointReference");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.GeometricVolume", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Location");

                    b.Property<Guid?>("LowerVerticalDistanceID")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpperVerticalDistanceID")
                        .HasColumnType("TEXT");

                    b.HasIndex("LowerVerticalDistanceID");

                    b.HasIndex("UpperVerticalDistanceID");

                    b.ToTable("GeometricVolume");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.Line", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Location");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.Point", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Location");

                    b.ToTable("Point");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.Surface", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Location");

                    b.ToTable("Surface");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.ObjectItems.Organisation", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.ObjectItems.ObjectItem");

                    b.Property<string>("NickName")
                        .HasColumnType("TEXT");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.ConeVolume", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.GeometricVolume");

                    b.Property<Guid>("DefiningSurfaceID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VertexPointID")
                        .HasColumnType("TEXT");

                    b.HasIndex("DefiningSurfaceID");

                    b.HasIndex("VertexPointID");

                    b.ToTable("ConeVolume");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.SphereVolume", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.GeometricVolume");

                    b.Property<Guid>("CentrePointID")
                        .HasColumnType("TEXT");

                    b.Property<double>("RadiusDimension")
                        .HasColumnType("REAL");

                    b.HasIndex("CentrePointID");

                    b.ToTable("SphereVolume");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.SurfaceVolume", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.GeometricVolume");

                    b.Property<Guid>("DefiningSurfaceID")
                        .HasColumnType("TEXT");

                    b.HasIndex("DefiningSurfaceID");

                    b.ToTable("SurfaceVolume");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.AbsolutePoint", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Point");

                    b.Property<double>("LatitudeCoordinate")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudeCoordinate")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("VerticalDistanceId")
                        .HasColumnType("TEXT");

                    b.HasIndex("VerticalDistanceId");

                    b.ToTable("AbsolutePoint");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.RelativePoint", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Point");

                    b.Property<Guid>("CoordinateSystemID")
                        .HasColumnType("TEXT");

                    b.Property<double>("XCoordinateDimension")
                        .HasColumnType("REAL");

                    b.Property<double>("YCoordinateDimension")
                        .HasColumnType("REAL");

                    b.Property<double>("ZCoordinateDimension")
                        .HasColumnType("REAL");

                    b.HasIndex("CoordinateSystemID");

                    b.ToTable("RelativePoint");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.CorridorArea", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Surface");

                    b.Property<Guid>("CenterLineID")
                        .HasColumnType("TEXT");

                    b.Property<double>("WidthDimension")
                        .HasColumnType("REAL");

                    b.HasIndex("CenterLineID");

                    b.ToTable("CorridorArea");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.Ellipse", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Surface");

                    b.Property<Guid>("CentrePointID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FirstConjugateDiameterPointID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SecondConjugateDiameterPointID")
                        .HasColumnType("TEXT");

                    b.HasIndex("CentrePointID");

                    b.HasIndex("FirstConjugateDiameterPointID");

                    b.HasIndex("SecondConjugateDiameterPointID");

                    b.ToTable("Ellipse");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.FanArea", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Surface");

                    b.Property<double>("MaximumRangeDimension")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumRangeDimension")
                        .HasColumnType("REAL");

                    b.Property<double>("OrientationAngle")
                        .HasColumnType("REAL");

                    b.Property<double>("SectorSizeAngle")
                        .HasColumnType("REAL");

                    b.Property<Guid>("VertexPointID")
                        .HasColumnType("TEXT");

                    b.HasIndex("VertexPointID");

                    b.ToTable("FanArea");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.OrbitArea", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Surface");

                    b.Property<Guid>("FirstPointID")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrbitAreaAlignmentCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SecondPointID")
                        .HasColumnType("TEXT");

                    b.Property<double>("WidthDimension")
                        .HasColumnType("REAL");

                    b.HasIndex("FirstPointID");

                    b.HasIndex("SecondPointID");

                    b.ToTable("OrbitArea");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.PolyArcArea", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Surface");

                    b.Property<double>("ArcRadiusDimension")
                        .HasColumnType("REAL");

                    b.Property<Guid>("BearingOriginPointID")
                        .HasColumnType("TEXT");

                    b.Property<double>("BeginBearingAngle")
                        .HasColumnType("REAL");

                    b.Property<Guid>("DefiningLineID")
                        .HasColumnType("TEXT");

                    b.Property<double>("EndBearingAngle")
                        .HasColumnType("REAL");

                    b.HasIndex("BearingOriginPointID");

                    b.HasIndex("DefiningLineID");

                    b.ToTable("PolyArcArea");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.PolygonArea", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Surface");

                    b.Property<Guid>("BoundingLineID")
                        .HasColumnType("TEXT");

                    b.HasIndex("BoundingLineID");

                    b.ToTable("PolygonArea");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.TrackArea", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.Geometry.Surface");

                    b.Property<Guid>("BeginPointID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EndPointID")
                        .HasColumnType("TEXT");

                    b.Property<double>("LeftWidthDimension")
                        .HasColumnType("REAL");

                    b.Property<double>("RightWidthDimension")
                        .HasColumnType("REAL");

                    b.HasIndex("BeginPointID");

                    b.HasIndex("EndPointID");

                    b.ToTable("TrackArea");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.ObjectItems.Unit", b =>
                {
                    b.HasBaseType("PR.Domain.Entities.C2IEDM.ObjectItems.Organisation");

                    b.Property<string>("FormalAbbreviatedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PR.Web.Persistence.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PR.Web.Persistence.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PR.Web.Persistence.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PR.Web.Persistence.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.LinePoint", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Line", "Line")
                        .WithMany("LinePoints")
                        .HasForeignKey("LineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Point");
                });

            modelBuilder.Entity("PR.Domain.Entities.PR.PersonAssociation", b =>
                {
                    b.HasOne("PR.Domain.Entities.PR.Person", "ObjectPerson")
                        .WithMany("SubjectPeople")
                        .HasForeignKey("ObjectPersonArchiveID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.PR.Person", "SubjectPerson")
                        .WithMany("ObjectPeople")
                        .HasForeignKey("SubjectPersonArchiveID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ObjectPerson");

                    b.Navigation("SubjectPerson");
                });

            modelBuilder.Entity("PR.Domain.Entities.PR.PersonComment", b =>
                {
                    b.HasOne("PR.Domain.Entities.PR.Person", "Person")
                        .WithMany("Comments")
                        .HasForeignKey("PersonArchiveID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.PointReference", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.CoordinateSystem", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.PointReference", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "OriginPoint")
                        .WithMany()
                        .HasForeignKey("OriginPointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "XVectorPoint")
                        .WithMany()
                        .HasForeignKey("XVectorPointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "YVectorPoint")
                        .WithMany()
                        .HasForeignKey("YVectorPointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginPoint");

                    b.Navigation("XVectorPoint");

                    b.Navigation("YVectorPoint");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.GeometricVolume", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Location", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.GeometricVolume", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.VerticalDistance", "LowerVerticalDistance")
                        .WithMany()
                        .HasForeignKey("LowerVerticalDistanceID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.VerticalDistance", "UpperVerticalDistance")
                        .WithMany()
                        .HasForeignKey("UpperVerticalDistanceID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LowerVerticalDistance");

                    b.Navigation("UpperVerticalDistance");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.Line", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Location", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.Line", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.Point", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Location", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.Point", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.Surface", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Location", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.Surface", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.ObjectItems.Organisation", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.ObjectItems.ObjectItem", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.ObjectItems.Organisation", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.ConeVolume", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Surface", "DefiningSurface")
                        .WithMany()
                        .HasForeignKey("DefiningSurfaceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.GeometricVolume", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.ConeVolume", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "VertexPoint")
                        .WithMany()
                        .HasForeignKey("VertexPointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefiningSurface");

                    b.Navigation("VertexPoint");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.SphereVolume", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "CentrePoint")
                        .WithMany()
                        .HasForeignKey("CentrePointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.GeometricVolume", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.SphereVolume", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentrePoint");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.SurfaceVolume", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Surface", "DefiningSurface")
                        .WithMany()
                        .HasForeignKey("DefiningSurfaceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.GeometricVolume", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.SurfaceVolume", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefiningSurface");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.AbsolutePoint", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.AbsolutePoint", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.VerticalDistance", "VerticalDistance")
                        .WithMany()
                        .HasForeignKey("VerticalDistanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("VerticalDistance");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.RelativePoint", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.CoordinateSystem", "CoordinateSystem")
                        .WithMany()
                        .HasForeignKey("CoordinateSystemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.RelativePoint", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoordinateSystem");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.CorridorArea", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Line", "CenterLine")
                        .WithMany()
                        .HasForeignKey("CenterLineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Surface", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.CorridorArea", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CenterLine");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.Ellipse", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "CentrePoint")
                        .WithMany()
                        .HasForeignKey("CentrePointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "FirstConjugateDiameterPoint")
                        .WithMany()
                        .HasForeignKey("FirstConjugateDiameterPointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Surface", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.Ellipse", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "SecondConjugateDiameterPoint")
                        .WithMany()
                        .HasForeignKey("SecondConjugateDiameterPointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentrePoint");

                    b.Navigation("FirstConjugateDiameterPoint");

                    b.Navigation("SecondConjugateDiameterPoint");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.FanArea", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Surface", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.FanArea", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "VertexPoint")
                        .WithMany()
                        .HasForeignKey("VertexPointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VertexPoint");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.OrbitArea", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "FirstPoint")
                        .WithMany()
                        .HasForeignKey("FirstPointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Surface", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.OrbitArea", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "SecondPoint")
                        .WithMany()
                        .HasForeignKey("SecondPointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstPoint");

                    b.Navigation("SecondPoint");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.PolyArcArea", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "BearingOriginPoint")
                        .WithMany()
                        .HasForeignKey("BearingOriginPointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Line", "DefiningLine")
                        .WithMany()
                        .HasForeignKey("DefiningLineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Surface", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.PolyArcArea", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BearingOriginPoint");

                    b.Navigation("DefiningLine");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.PolygonArea", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Line", "BoundingLine")
                        .WithMany()
                        .HasForeignKey("BoundingLineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Surface", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.PolygonArea", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoundingLine");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.TrackArea", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "BeginPoint")
                        .WithMany()
                        .HasForeignKey("BeginPointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Point", "EndPoint")
                        .WithMany()
                        .HasForeignKey("EndPointID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.C2IEDM.Geometry.Surface", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.Geometry.TrackArea", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeginPoint");

                    b.Navigation("EndPoint");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.ObjectItems.Unit", b =>
                {
                    b.HasOne("PR.Domain.Entities.C2IEDM.ObjectItems.Organisation", null)
                        .WithOne()
                        .HasForeignKey("PR.Domain.Entities.C2IEDM.ObjectItems.Unit", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PR.Domain.Entities.PR.Person", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ObjectPeople");

                    b.Navigation("SubjectPeople");
                });

            modelBuilder.Entity("PR.Domain.Entities.C2IEDM.Geometry.Line", b =>
                {
                    b.Navigation("LinePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
