// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PR.Persistence.EntityFrameworkCore.SqlServer;

#nullable disable

namespace PR.Persistence.EntityFrameworkCore.SqlServer.Migrations
{
    [DbContext(typeof(PRDbContext))]
    [Migration("20260327140845_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PR.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Dead")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Superseded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PR.Domain.Entities.PersonAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ObjectPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ObjectPersonObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectPersonObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Superseded")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ObjectPersonId");

                    b.HasIndex("SubjectPersonId");

                    b.ToTable("PersonAssociations");
                });

            modelBuilder.Entity("PR.Domain.Entities.PersonAssociation", b =>
                {
                    b.HasOne("PR.Domain.Entities.Person", "ObjectPerson")
                        .WithMany("SubjectPeople")
                        .HasForeignKey("ObjectPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PR.Domain.Entities.Person", "SubjectPerson")
                        .WithMany("ObjectPeople")
                        .HasForeignKey("SubjectPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectPerson");

                    b.Navigation("SubjectPerson");
                });

            modelBuilder.Entity("PR.Domain.Entities.Person", b =>
                {
                    b.Navigation("ObjectPeople");

                    b.Navigation("SubjectPeople");
                });
#pragma warning restore 612, 618
        }
    }
}
